### ISSUE TITLE
FT 01 US 01 - Visualizar publicações próprias

### ISSUE THREAD

**Issue by MarcoRLK** [UnbFeelings/unb-feelings-web-app#19]
Eu, como aluno, desejo visualizar as minhas publicações de sentimentos com o objetivo de recordar como me sinto.

**Critérios de Aceitação**
- [x] Visualizar o texto da publicação
- [x] Visualizar o sentimento
- [x] Visualizar hashtags
- [x] Visualizar através de _timeline_
- [x] Não é necessário ter uma página para a publicação, apenas a _timeline_ é suficiente.

**Comment by altjohndev** [comment]
1. Visualizar através de _timeline_
1. Não é necessário ter uma página para a publicação, apenas a _timeline_ é suficiente.
