### ISSUE TITLE
FT 01 US 02 - Visualizar publicações de sentimentos de outros usuários

### ISSUE THREAD

**Issue by MarcoRLK** [UnbFeelings/unb-feelings-web-app#20]
Eu, como aluno, desejo visualizar as publicações de sentimentos de outro aluno anonimamente com o objetivo de entender como ele se sente.

**Critérios de Aceitação**
- [x] Não visualizar o texto da publicação
- [x] Visualizar um nome aleatório para o perfil acessado
- [x] Visualizar o sentimento
- [x] Visualizar hashtags
- [x] Visualizar através de timeline
- [x] Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
- [x] Avatar aleatório (de acordo com o nome)

**Comment by altjohndev** [comment]
1. Visualizar através de timeline
1. Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
1. Avatar aleatório (de acordo com o nome)
