### ISSUE TITLE
FT 01 US 03 - Visualizar publicações de sentimentos de uma disciplina

### ISSUE THREAD

**Issue by MarcoRLK** [UnbFeelings/unb-feelings-web-app#21]
Eu, como aluno, desejo visualizar as publicações de sentimentos de uma determinada disciplina, com o objetivo de entender seu impacto nos sentimentos dos alunos.

**Critérios de Aceitação**
- [ ] Não visualizar o texto da publicação
- [ ] Visualizar o nome da disciplina
- [ ] Visualizar o sentimento
- [ ] Visualizar hashtags
- [ ] Visualizar através de timeline
- [ ] Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
- [ ] Ao clicar no sentimento, deve levar ao perfil do usuário que publicou o sentimento
- [ ] Avatares aleatórios (de acordo com o nome)

**Comment by altjohndev** [comment]
1. Visualizar através de timeline
1. Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
1. Ao clicar no sentimento, deve levar ao perfil do usuário que publicou o sentimento
1. Avatares aleatórios (de acordo com o nome)

**Comment by MarcoRLK** [comment]
Merged in PR https://github.com/UnbFeelings/unb-feelings-web-app/pull/35
