### ISSUE TITLE
FT01 US 04 - Visualizar publicações de sentimentos de toda a universidade

### ISSUE THREAD

**Issue by MarcoRLK** [UnbFeelings/unb-feelings-web-app#22]
Eu, como aluno, desejo visualizar as publicações de sentimentos da UnB, com o objetivo de avaliar dos alunos universidade se sentem como um todo.

**Critérios de Aceitação**
- [x] Visualizar todas as publicações dos usuários
- [x] Não visualizar o texto da publicação
- [x] Visualizar o sentimento
- [x] Visualizar hashtags
- [x] Visualizar através de timeline
- [x] Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
- [x] Ao clicar no sentimento, deve levar ao perfil do usuário que publicou o sentimento
- [x] Avatares aleatórios (de acordo com o nome)

**Comment by altjohndev** [comment]
1. Visualizar através de timeline
1. Não é necessário ter uma página para a publicação, apenas a timeline é suficiente.
1. Ao clicar no sentimento, deve levar ao perfil do usuário que publicou o sentimento
1. Avatares aleatórios (de acordo com o nome)
