### ISSUE TITLE
FT02 US06 - Visualizar meu gráfico semanal

### ISSUE THREAD

**Issue by MatheusRich** [UnbFeelings/unb-feelings-web-app#30]
Eu, como aluno, desejo visualizar um gráfico que mostre os dias mais estressantes com o objetivo de compreender como me sinto durante a semana.

**Critérios de Aceitação**
- [x] Visualizar todos os dias da semana (seg-dom)
- [x] Visualizar sentimentos bons e ruins.

**Comment by fabio1079** [comment]
Só não está como gráfico, mas cumpre os Critérios de Aceitação
