### ISSUE TITLE
FT02 US10 - Gráfico de Disciplinas da UnB

### ISSUE THREAD

**Issue by MatheusRich** [UnbFeelings/unb-feelings-web-app#34]
Eu, como usuário, desejo visualizar quais disciplinas mais desgastam e/ou motivam na UnB, com o objetivo de compreender como as matérias afetam os alunos.

**Critérios de Aceitação**
- [x] Visualizar apenas disciplinas que foram citadas em algum post.
- [x] Visualizar separadamente disciplinas motivadores e desgastantes.

**Comment by MarcoRLK** [comment]
Merged in Pull Request https://github.com/UnbFeelings/unb-feelings-web-app/pull/44
