### ISSUE TITLE
TD - Visualizar perfil

### ISSUE THREAD

**Issue by Rdlenke** [UnbFeelings/unb-feelings-web-app#70]
Eu, como usuário, desejo visualizar o meu perfil e o perfil de outros usuários para poder interagir com eles.

**Critérios de Aceitação**

- [ ] O usuário deve ser capaz de visualizar seu próprio perfil, visualizando seu nome gerado e sua imagem gerada.
- [ ] O usuário deve ser capaz de visualizar o perfil de outros usuários, visualizando as imagens geradas e o nome gerado para eles.

**Comment by joaopaulonsoares** [comment]
Foi encontrado a implementação após uma depuração mais refinada.
